///----------------------------------------------------------------
// CLASS :
//
// DESCRIPTION :
//
// ALGORITHM :
//
// INHERITED CLASSES :
//
// INCLUDED CLASSES :
//
// USED CLASSES :
//
// EXCEPTIONS GENERATED :
//
// EXCEPTIONS CAPTURED :
//
// GLOBALS VARIABLES:
//
// VARIABLES :
//
// OPERATIONS :
//
// NOTES :
//
//----------------------------------------------------------------
